### ISSUE TITLE
"Cannot read property 'dispose' of undefined" when exiting VC

### ISSUE THREAD

**Issue by rxl881** [matrix-org/matrix-vr-demo#23]
Seen when exiting VC (to lobby):

```
componentDidMount @ bundle.js:120488
bundle.js:77201 Uncaught TypeError: Cannot read property 'dispose' of undefined
    at disposeMaterial (https://10.9.64.52:9090/bundle.js:77201:12)
    at NewComponent.remove (https://10.9.64.52:9090/bundle.js:77155:6)
    at HTMLElement.value (https://10.9.64.52:9090/bundle.js:81521:18)
    at bound (https://10.9.64.52:9090/bundle.js:86696:18)
    at Array.forEach (native)
    at HTMLElement.value (https://10.9.64.52:9090/bundle.js:81200:37)
    at removeChild (https://10.9.64.52:9090/bundle.js:106900:15)
    at Object.processUpdates (https://10.9.64.52:9090/bundle.js:107044:12)
    at Object.dangerouslyProcessChildrenUpdates [as processChildrenUpdates] (https://10.9.64.52:9090/bundle.js:107935:28)
    at processQueue (https://10.9.64.52:9090/bundle.js:111478:30)
bundle.js:77201 Uncaught TypeError: Cannot read property 'dispose' of undefined
    at disposeMaterial (https://10.9.64.52:9090/bundle.js:77201:12)
    at NewComponent.remove (https://10.9.64.52:9090/bundle.js:77155:6)
    at HTMLElement.value (https://10.9.64.52:9090/bundle.js:81521:18)
    at bound (https://10.9.64.52:9090/bundle.js:86696:18)
    at Array.forEach (native)
    at HTMLElement.value (https://10.9.64.52:9090/bundle.js:81200:37)
    at removeChild (https://10.9.64.52:9090/bundle.js:106900:15)
    at Object.processUpdates (https://10.9.64.52:9090/bundle.js:107044:12)
    at Object.dangerouslyProcessChildrenUpdates [as processChildrenUpdates] (https://10.9.64.52:9090/bundle.js:107935:28)
    at processQueue (https://10.9.64.52:9090/bundle.js:111478:30)
```

**Comment by ara4n** [comment]
fixed by @rxl881 somewhere :)
